In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/raw/ventas_raw.csv')
df

,id_venta,numero_linea,fecha_venta,id_cliente,id_producto,id_tienda,nombre_tienda,ciudad,empresa,nombre_producto,...,precio_unitario,descuento,genero_cliente,tipo_cliente,talla,metodo_pago,canal,temporada,tipo_prenda,departamento
0,V003565,1,2024-02-04,C00909,P0003,T007,KOAJ San Pedro Plaza,Neiva,KOAJ,Jean mom,...,"179.000,00",0.00,Hombre,Local,40,Tarjeta crédito,Tienda física,Temporada regular,Pantalón,Huila
1,V002111,2,2023-01-01,C00348,P0008,T040,KOAJ Andino,Bogotá,KOAJ,Chaqueta bomber,...,"211000,00",0.00,Hombre,Local,M,Efectivo,Tienda física,Regreso a clases,Chaqueta,Bogotá D.C.
2,V002185,1,2023-03-31,C00804,P0009,T003,KOAJ Ocean Mall,Santa Marta,KOAJ,Camisa casual,...,"128000,00",0.00,Mujer,Turista,XXL,Efectivo,Tienda física,Día del Padre,Camisa,Magdalena
3,V002828,1,2024-05-13,C00951,P0014,T034,KOAJ Viva Barranquilla,Barranquilla,KOAJ,Jogger,...,"133000,00",NaN,Hombre,Local,38,Tarjeta crédito,Tienda física,Black Friday,Pantalón,Atlántico
4,V001693,1,2023-11-14,C01804,P0007,T030,KOAJ Cacique,Bucaramanga,KOAJ,Gorra,...,"61000,00",0.00,Mujer,Local,XL,Tarjeta crédito,Tienda física,Temporada regular,Accesorio,Santander
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,V003749,1,2024-10-19,C01395,P0004,T005,KOAJ Viva Sincelejo,Sincelejo,KOAJ,Jean skinny,...,"180000,00",0.00,Mujer,Local,38,Tarjeta crédito,Tienda física,Temporada de diciembre,Pantalón,Sucre
5996,V002277,2,2025-12-04,C02228,P0009,T019,KOAJ Primavera Urbana,Villavicencio,KOAJ,Camisa casual,...,"130.000,00",0.00,Mujer,Local,S,Tarjeta crédito,Tienda física,Temporada de diciembre,Camisa,Meta
5997,V001587,1,2025-07-11,C01323,P0018,T018,KOAJ Mall Plaza,Cartagena,KOAJ,Camiseta básica,...,77000,0.05,Mujer,Local,M,Tarjeta débito,Tienda física,Temporada regular,Camiseta,Bolívar
5998,V001576,1,2024-01-15,C02669,P0021,T018,KOAJ Mall Plaza,Cartagena,KOAJ,Polo,...,"126000,00",0.05,Mujer,Local,L,Efectivo,Tienda física,Temporada regular,Polo,Bolívar
5999,V001850,1,2025-01-16,C02175,P0010,T004,KOAJ Unicentro,Armenia,KOAJ,Short,...,"99000,00",0.00,Hombre,Local,32,Transferencia,Tienda física,Temporada regular,Short,Quindío

In [2]:
# Revisar el tamaño del DataFrame

print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

Filas: 6000
Columnas: 22

In [3]:
# Revisar la información del DataFrame 

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         6000 non-null   str
 1   numero_linea     6000 non-null   int64
 2   fecha_venta      6000 non-null   str
 3   id_cliente       6000 non-null   str
 4   id_producto      6000 non-null   str
 5   id_tienda        6000 non-null   str
 6   nombre_tienda    6000 non-null   str
 7   ciudad           5997 non-null   str
 8   empresa          6000 non-null   str
 9   nombre_producto  5997 non-null   str
 10  categoria        5998 non-null   str
 11  cantidad         6000 non-null   int64
 12  precio_unitario  6000 non-null   str
 13  descuento        5988 non-null   float64
 14  genero_cliente   5998 non-null   str
 15  tipo_cliente     6000 non-null   str
 16  talla            5985 non-null   str
 17  metodo_pago      5998 non-null   str
 18  canal            6000 non-null   str
 19  temporada        6000 non-null   str
 20  tipo_prenda      6000 non-null   str
 21  departamento     6000 non-null   str
dtypes: float64(1), int64(2), str(19)
memory usage: 1.0 MB

In [4]:
# Verificar los tipos de datos de cada columna

df.dtypes

id_venta               str
numero_linea         int64
fecha_venta            str
id_cliente             str
id_producto            str
id_tienda              str
nombre_tienda          str
ciudad                 str
empresa                str
nombre_producto        str
categoria              str
cantidad             int64
precio_unitario        str
descuento          float64
genero_cliente         str
tipo_cliente           str
talla                  str
metodo_pago            str
canal                  str
temporada              str
tipo_prenda            str
departamento           str
dtype: object

In [5]:
# Explorar los datos

df.head(10)   
df.tail(10)   
df.sample(10)

,id_venta,numero_linea,fecha_venta,id_cliente,id_producto,id_tienda,nombre_tienda,ciudad,empresa,nombre_producto,...,precio_unitario,descuento,genero_cliente,tipo_cliente,talla,metodo_pago,canal,temporada,tipo_prenda,departamento
1105,V000464,1,2023-03-25,C00280,P0005,T033,KOAJ Parque Arboleda,Pereira,KOAJ,Falda,...,"110.000,00",0.05,Hombre,Local,XXL,Efectivo,Tienda física,Temporada regular,Falda,Risaralda
3879,V000882,1,2025-11-30,C01454,P0021,T001,KOAJ Premium Plaza,Medellín,KOAJ,Polo,...,"123000,00",0.30,Mujer,Local,XXL,Tarjeta débito,Tienda física,Vacaciones,Polo,Antioquia
4677,V001639,1,2023-11-11,C02230,P0015,T004,KOAJ Unicentro,Armenia,KOAJ,Jean straight,...,"171.000,00",0.20,Mujer,Local,40,Tarjeta débito,Tienda física,Temporada regular,Pantalón,Quindío
970,V000180,2,2023-03-01,C01822,P0018,T004,KOAJ Unicentro,Armenia,KOAJ,Camiseta básica,...,"74000,00",0.00,Hombre,Local,S,Tarjeta débito,Online,Día del Padre,Camiseta,Quindío
2746,V000858,1,2024-09-18,C02776,P0015,T002,KOAJ Multicentro,Ibagué,KOAJ,Jean straight,...,175000,0.00,Hombre,Local,38,Efectivo,Tienda física,Vacaciones,Pantalón,Tolima
2913,V001712,1,2023-03-09,C02524,P0003,T039,KOAJ Alamedas,Montería,KOAJ,Jean mom,...,"175.000,00",0.00,Mujer,Local,30,Tarjeta crédito,Tienda física,Temporada regular,Pantalón,Córdoba
181,V000440,1,2023-06-26,C02245,P0020,T006,KOAJ Único,Pasto,KOAJ,Camiseta estampada,...,"77000,00",0.00,Hombre,Local,L,Tarjeta débito,Tienda física,Temporada regular,Camiseta,Nariño
3878,V002305,1,2025-05-27,C02748,P0021,T010,KOAJ Terraplaza,Popayán,KOAJ,Polo,...,"118000,00",0.20,Hombre,Local,XS,Efectivo,Tienda física,Black Friday,Polo,Cauca
4389,V000119,2,2025-07-08,C02154,P0022,T004,KOAJ Unicentro,Armenia,KOAJ,Tenis casuales,...,"198.000,00",0.00,Mujer,Turista,M,Tarjeta crédito,Tienda física,Black Friday,Calzado,Quindío
149,V003214,2,2025-03-18,C01839,P0021,T023,KOAJ Jardín Plaza,Cali,KOAJ,Polo,...,"121000,00",0.00,Mujer,Local,L,Efectivo,Tienda física,Temporada regular,Polo,Valle del Cauca

In [6]:
# Realizar un analisis estadistico

df.describe()           
df.describe(include='all')

,id_venta,numero_linea,fecha_venta,id_cliente,id_producto,id_tienda,nombre_tienda,ciudad,empresa,nombre_producto,...,precio_unitario,descuento,genero_cliente,tipo_cliente,talla,metodo_pago,canal,temporada,tipo_prenda,departamento
count,6000,6000.000000,6000,6000,6000,6000,6000,5997,6000,5997,...,6000,5988.000000,5998,6000,5985,5998,6000,6000,6000,6000
unique,3798,NaN,1059,2052,26,43,53,27,3,36,...,467,NaN,4,4,13,8,4,12,19,26
top,V001446,NaN,2024-11-24,C01044,P0022,T004,KOAJ Unicentro,Armenia,KOAJ,Tenis casuales,...,"75000,00",NaN,Mujer,Local,XS,Tarjeta crédito,Tienda física,Temporada regular,Pantalón,Quindío
freq,4,NaN,17,12,263,869,869,989,5900,262,...,72,NaN,3415,5096,778,2222,5239,3623,1345,987
mean,NaN,1.445667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.059193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.635963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.101879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Revisar valores nulos

nulos = df.isnull().sum()
print(f"Nulos:\n{nulos[nulos > 0]}")
print(f"\nTotal filas: {len(df)}")
print(f"\nPorcentaje de nulos por columna:")
print((df.isnull().sum() / len(df) * 100).round(2))

Nulos:
ciudad              3
nombre_producto     3
categoria           2
descuento          12
genero_cliente      2
talla              15
metodo_pago         2
dtype: int64

Total filas: 6000

Porcentaje de nulos por columna:
id_venta           0.00
numero_linea       0.00
fecha_venta        0.00
id_cliente         0.00
id_producto        0.00
id_tienda          0.00
nombre_tienda      0.00
ciudad             0.05
empresa            0.00
nombre_producto    0.05
categoria          0.03
cantidad           0.00
precio_unitario    0.00
descuento          0.20
genero_cliente     0.03
tipo_cliente       0.00
talla              0.25
metodo_pago        0.03
canal              0.00
temporada          0.00
tipo_prenda        0.00
departamento       0.00
dtype: float64

In [8]:
# Revisar valores duplicados

duplicados = df.duplicated(subset=['id_venta', 'numero_linea']).sum()
print(f"Duplpicados exactos: {df.duplicated().sum()}")
print(f"\nDuplicados por id_venta + numero_linea: {duplicados}")

Duplpicados exactos: 7

Duplicados por id_venta + numero_linea: 7

In [9]:
# Valores unicos por columna

columnas_categorias = ['empresa', 'ciudad', 'categoria', 'canal', 
                       'metodo_pago', 'temporada', 'genero_cliente', 
                       'tipo_cliente', 'tipo_prenda', 'departamento']

for col in columnas_categorias:
    print(f"{col}: {df[col].nunique()} valores únicos")
    print(f"  {sorted(df[col].dropna().unique())}\n")

empresa: 3 valores únicos
  ['KOAJ', 'KOAJ ', 'koaj']

ciudad: 27 valores únicos
  ['  Barranquilla  ', '  Bucaramanga  ', '  Cali  ', '  Ibagué  ', '  Medellín  ', '  Montería  ', '  Popayán  ', 'Armenia', 'Barranquilla', 'Bogotá', 'Bucaramanga', 'Cali', 'Cartagena', 'Cúcuta', 'Ibagué', 'Manizales', 'Medellín', 'Montería', 'Neiva', 'Pasto', 'Pereira', 'Popayán', 'Riohacha', 'Santa Marta', 'Sincelejo', 'Valledupar', 'Villavicencio']

categoria: 23 valores únicos
  ['  Accesorios  ', '  Blusas  ', '  Calzado  ', '  Camisas  ', '  Camisetas  ', '  Faldas  ', '  Jeans  ', '  Pantalones  ', '  Vestidos  ', 'Accesorios', 'Blusas', 'Buzos', 'Calzado', 'Camisas', 'Camisetas', 'Chaquetas', 'Deportivo', 'Faldas', 'Jeans', 'Pantalones', 'Shorts', 'Tops', 'Vestidos']

canal: 4 valores únicos
  ['  Online  ', '  Tienda física  ', 'Online', 'Tienda física']

metodo_pago: 8 valores únicos
  ['  Efectivo  ', '  Tarjeta crédito  ', '  Tarjeta débito  ', '  Transferencia  ', 'Efectivo', 'Tarjeta crédito', 'Tarjeta débito', 'Transferencia']

temporada: 12 valores únicos
  ['  Día de la Madre  ', '  Regreso a clases  ', '  Temporada de diciembre  ', '  Temporada regular  ', '  Vacaciones  ', 'Black Friday', 'Día de la Madre', 'Día del Padre', 'Regreso a clases', 'Temporada de diciembre', 'Temporada regular', 'Vacaciones']

genero_cliente: 4 valores únicos
  ['  Hombre  ', '  Mujer  ', 'Hombre', 'Mujer']

tipo_cliente: 4 valores únicos
  ['  Local  ', '  Turista  ', 'Local', 'Turista']

tipo_prenda: 19 valores únicos
  ['  Buzo  ', '  Camisa  ', '  Camiseta  ', '  Pantalón  ', '  Short  ', 'Accesorio', 'Blusa', 'Buzo', 'Calzado', 'Camisa', 'Camiseta', 'Chaqueta', 'Conjunto', 'Falda', 'Pantalón', 'Polo', 'Short', 'Top', 'Vestido']

departamento: 26 valores únicos
  ['  Antioquia  ', '  Atlántico  ', '  Córdoba  ', '  Quindío  ', '  Sucre  ', '  Tolima  ', 'Antioquia', 'Atlántico', 'Bogotá D.C.', 'Bolívar', 'Caldas', 'Cauca', 'Cesar', 'Córdoba', 'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Nariño', 'Norte de Santander', 'Quindío', 'Risaralda', 'Santander', 'Sucre', 'Tolima', 'Valle del Cauca']

In [10]:
# Verificar los precios

print(f"Tipo de dato de precio: {df['precio_unitario'].dtype}")
print(f"\nPrimeros valores:\n{df['precio_unitario'].head(10)}")
print(f"\nRango: {df['precio_unitario'].min()} - {df['precio_unitario'].max()}")

Tipo de dato de precio: str

Primeros valores:
0    179.000,00
1     211000,00
2     128000,00
3     133000,00
4      61000,00
5        161000
6     209000,00
7     74.000,00
8    207.000,00
9        170000
Name: precio_unitario, dtype: str

Rango: 100.000,00 - 99000,00

In [11]:
# Conversion de los precios para mejor visualizacion

df['precio_unitario'] = df['precio_unitario'].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)

precios_negativos = df[df['precio_unitario'] < 0].shape[0]
print(f"\nPrecios negativos: {precios_negativos}")

print(f"\nRango: {df['precio_unitario'].min()} - {df['precio_unitario'].max()}")
df['precio_unitario']

Precios negativos: 0

Rango: 53000.0 - 227000.0

0       179000.0
1       211000.0
2       128000.0
3       133000.0
4        61000.0
          ...
5995    180000.0
5996    130000.0
5997     77000.0
5998    126000.0
5999     99000.0
Name: precio_unitario, Length: 6000, dtype: float64